create database Technnical_Project;

use Technnical_Project;

-- What is the average price for each combination of room type and neighbourhood group?
SELECT room_type, neighbourhood_group, AVG(price) AS average_price
FROM clean_airbnb_data
GROUP BY room_type, neighbourhood_group;

-- Which neighbourhoods have the highest number of listings?
SELECT neighbourhood, COUNT(*) AS listing_count
FROM clean_airbnb_data
GROUP BY neighbourhood
ORDER BY listing_count DESC
LIMIT 5;

-- Who are the top hosts with the most listings?
SELECT host_name, COUNT(*) AS listing_count
FROM clean_airbnb_data
GROUP BY host_name
ORDER BY listing_count DESC
LIMIT 5;

-- What is the estimated revenue generated by each host based on the number of reviews and the average price of their listings?
SELECT host_name, SUM(number_of_reviews * price) AS estimated_revenue
FROM clean_airbnb_data
GROUP BY host_name
ORDER BY estimated_revenue DESC
LIMIT 5;

-- Do instant bookable listings have higher booking rates compared to non-instant bookable listings?
SELECT instant_bookable, AVG(reviews_per_month) AS avg_reviews
FROM clean_airbnb_data
GROUP BY instant_bookable;

-- How has the average price of listings changed over the years?
SELECT Construction_year, AVG(price) AS avg_price
FROM clean_airbnb_data
WHERE Construction_year IS NOT NULL
GROUP BY Construction_year
ORDER BY Construction_year;

-- Do listings with more flexible cancellation policies have higher booking rates?
SELECT cancellation_policy, AVG(reviews_per_month) AS avg_reviews
FROM clean_airbnb_data
GROUP BY cancellation_policy;

-- Which neighbourhood groups generate the highest revenue based on the number of reviews and average price?
SELECT neighbourhood_group, SUM(number_of_reviews * price) AS total_revenue
FROM clean_airbnb_data
GROUP BY neighbourhood_group
ORDER BY total_revenue DESC;

-- What is the average price for listings based on different ranges of minimum nights required for booking?
SELECT 
  CASE 
    WHEN minimum_nights BETWEEN 1 AND 3 THEN '1-3 Nights'
    WHEN minimum_nights BETWEEN 4 AND 7 THEN '4-7 Nights'
    WHEN minimum_nights BETWEEN 8 AND 14 THEN '8-14 Nights'
    ELSE '15+ Nights'
  END AS nights_range,
  AVG(price) AS average_price
FROM clean_airbnb_data
GROUP BY nights_range
ORDER BY nights_range;

-- What is the average booking rate for listings of different construction years?
SELECT construction_year, AVG(price) AS avg_booking_rate
FROM clean_airbnb_data
GROUP BY construction_year;




